financial_analysis/urls.py
from django.urls import path

from . import views

app_name = 'financial_analysis'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('company/<int:pk>', views.CompanyView.as_view(), name='company'),
    path('fstatement_detail/<int:pk>', views.FstatementView.as_view(), name='fstatement'),
]

techpit/urls.py
from django.contrib import admin
from django.urls import path, include #includeを追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('financial_analysis.urls')),
]

financial_analysis/models.py
from django.db import models
import numpy

class Company(models.Model):
    name = models.CharField("会社名", max_length=30, blank=False)

    def __str__(self):
        return str(self.name)


class Fstatement(models.Model):
    company = models.ForeignKey(Company, on_delete=models.PROTECT)
    fiscal_year = models.DateField("決算日")
    bs_current_assets = models.IntegerField("流動資産（百万円）", default=0)
    bs_fixed_assets = models.IntegerField("固定資産（百万円）", default=0)
    bs_deferred_assets = models.IntegerField("繰延資産（百万円）", default=0)
    bs_current_liabilities = models.IntegerField("流動負債（百万円）", default=0)
    bs_fixed_liabilities = models.IntegerField("固定負債（百万円）", default=0)
    bs_net_assets = models.IntegerField("純資産（百万円）", default=0)
    pl_gross_sales = models.IntegerField("総売上（百万円）", default=0)
    pl_gross_profit = models.IntegerField("売上総利益（百万円）", default=0)
    pl_operating_profit = models.IntegerField("営業利益（百万円）", default=0)
    pl_ordinary_income = models.IntegerField("経常利益（百万円）", default=0)
    pl_income_before_tax = models.IntegerField("税引前当期純利益（百万円）", default=0)
    pl_net_income = models.IntegerField("当期純利益（百万円）", default=0)
    cf_operating = models.IntegerField("営業ＣＦ（百万円）", default=0)
    cf_investment = models.IntegerField("投資ＣＦ（百万円）", default=0)
    cf_finance = models.IntegerField("財務ＣＦ（百万円）", default=0)

    def __str__(self):
        return str(self.company) + '決算日：【 ' + str(self.fiscal_year) + '】'

    # ========以下をすべて追加========

    # 総資産を計算
    def bs_total_assets(self):
        f = self.bs_current_assets + self.bs_fixed_assets + self.bs_deferred_assets
        return f

    # 総資産に対する流動資産の比率を計算（流動資産／総資産）
    def current_assets_rate(self):
        f = numpy.float64(self.bs_current_assets) / self.bs_total_assets() * 100
        return f

    # 総資産に対する固定資産の比率を計算（固定資産／総資産）
    def fixed_assets_rate(self):
        f = numpy.float64(self.bs_fixed_assets) / self.bs_total_assets() * 100
        return f

    # 総資産に対する繰延資産の比率を計算（繰延資産／総資産）
    def deferred_assets_rate(self):
        f = numpy.float64(self.bs_deferred_assets) / self.bs_total_assets() * 100
        return f

    # 総資産に対する流動負債の比率を計算（流動負債／総資産）
    def current_liabilities_rate(self):
        f = numpy.float64(self.bs_current_liabilities) / self.bs_total_assets() * 100
        return f

    # 総資産に対する固定負債の比率を計算（固定負債／総資産）
    def fixed_liabilities_rate(self):
        f = numpy.float64(self.bs_fixed_liabilities) / self.bs_total_assets() * 100
        return f

    # 総資産に対する純資産の比率を計算（純資産／総資産）
    def net_assets_rate(self):
        f = numpy.float64(self.bs_net_assets) / self.bs_total_assets() * 100
        return f

    # 総売上高合計に対する売上総利益の比率を計算（売上総利益／総売上）
    def gross_profit_rate(self):
        f = numpy.float64(self.pl_gross_profit) / self.pl_gross_sales * 100
        return f

    # 総売上高合計に対する営業利益の比率を計算（営業利益／総売上）
    def operating_profit_rate(self):
        f = numpy.float64(self.pl_operating_profit) / self.pl_gross_sales * 100
        return f

    # 総売上高合計に対する経常利益の比率を計算（経常利益／総売上）
    def ordinary_income_rate(self):
        f = numpy.float64(self.pl_ordinary_income) / self.pl_gross_sales * 100
        return f

    # 総売上高合計に対する税引前当期純利益の比率を計算（税引前当期純利益／総売上）
    def income_before_tax_rate(self):
        f = numpy.float64(self.pl_income_before_tax) / self.pl_gross_sales * 100
        return f

    # 総売上高合計に対する当期純利益の比率を計算（当期純利益／総売上）
    def net_income_rate(self):
        f = numpy.float64(self.pl_net_income) / self.pl_gross_sales * 100
        return f

    # キャッシュフロー合計を計算
    def cf_total_amount(self):
        f = self.cf_operating + self.cf_investment + self.cf_finance
        return f

    # 流動比率を計算
    def current_rate(self):
        if self.bs_current_liabilities > 0:
            f = numpy.float64(self.bs_current_assets) / self.bs_current_liabilities * 100
        else:
            f = '-'
        return f

    # ＲＯＥを計算
    def roe(self):
        f = numpy.float64(self.pl_operating_profit) / self.bs_net_assets * 100
        return f

    #　ＲＯＡを計算
    def roa(self):
        f = numpy.float64(self.pl_operating_profit) / self.bs_total_assets() * 100
        return f

financial_analysis/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import TemplateView, DetailView
from .models import Fstatement
from .models import Company
from django.views.generic.list import MultipleObjectMixin

class IndexView(TemplateView):
    template_name = 'financial_analysis/index.html'

    def get_context_data(self, **kwargs):
        fstatement_list = Fstatement.objects.all().order_by('company')
        params = {
            'fstatement_list': fstatement_list,
        }
        return params

class CompanyView(DetailView, MultipleObjectMixin):
    model = Company
    paginate_by = 4

    def get_context_data(self, **kwargs):
        object_list = Fstatement.objects.filter(company=kwargs['object']).order_by('-fiscal_year')
        context = super(CompanyView, self).get_context_data(object_list=object_list, **kwargs)
        
        return context

class FstatementView(DetailView):
    model = Fstatement

templates/financial_analysis/base.html
{% load static %}
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <title>financial_analysis</title>

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css" />
    <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">financial_analysis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'financial_analysis:index' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        Company
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% for item in company_list %}
                        <a class="dropdown-item" href="{% url 'financial_analysis:company' item.id %}">{{ item.name }}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <main>
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/financial_analysis/company_detail.html
{% extends 'financial_analysis/base.html' %} {% load humanize %} {% block content %}
<h1>{{ company_name }}の決算データ</h1>

<section class="tables">
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-header d-flex">
            <h3 class="h4">決算推移</h3>
          </div>
          <!--card header-->
          <div class="card-body">
            <div class="table-responsive">
              <table width="100%" class="table table-bordered display nowrap">
                <tr>
                  <th rowspan="2" width="120px"></th>
                  {% for item in object_list reversed %}
                  <th colspan="2" width="120px" class="center">
                    <a href="{% url 'financial_analysis:fstatement' item.pk %}">{{ item.fiscal_year }}</a>
                  </th>
                  {% endfor %}
                </tr>
                <tr style="text-align: center;">
                  <td width="120px">金額</td>
                  <td width="100px">比率</td>
                  <td width="120px">金額</td>
                  <td width="100px">比率</td>
                  <td width="120px">金額</td>
                  <td width="100px">比率</td>
                  <td width="120px">金額</td>
                  <td width="100px">比率</td>
                </tr>
                <tr>
                  <td colspan="9" class="bg-title" style="text-align: left;">貸借対照表</td>
                </tr>
                <tr>
                  <td colspan="9" class="title" style="text-align: left;">資産の部</td>
                </tr>
                <tr>
                  <th class="lv1-bottom">流動資産</th>
                  {% for item in object_list reversed %}
                  <td class="amount lv1-bottom">{{ item.bs_current_assets|intcomma }}</td>
                  <td class="rate lv1-bottom">{{ item.current_assets_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th class="lv1-bottom">固定資産</th>
                  {% for item in object_list reversed %}
                  <td class="amount lv1-bottom">{{ item.bs_fixed_assets|intcomma }}</td>
                  <td class="rate lv1-bottom">{{ item.fixed_assets_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th class="lv1-bottom">繰延資産</th>
                  {% for item in object_list reversed %}
                  <td class="amount lv1-bottom">{{ item.bs_deferred_assets|intcomma }}</td>
                  <td class="rate lv1-bottom">{{ item.deferred_assets_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th class="lv1-bottom">総資産</th>
                  {% for item in object_list reversed %}
                  <td class="amount lv1-bottom">{{ item.bs_total_assets|intcomma }}</td>
                  <td class="rate lv1-bottom">100％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td colspan="9" class="title" style="text-align: left;">負債の部</td>
                </tr>
                <tr>
                  <th>流動負債</th>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.bs_current_liabilities|intcomma }}</td>
                  <td class="rate">{{ item.current_liabilities_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th>固定負債</th>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.bs_fixed_liabilities|intcomma }}</td>
                  <td class="rate">{{ item.fixed_liabilities_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td colspan="9" class="title">純資産の部</td>
                </tr>
                <tr>
                  <th class="lv1-bottom">株主資本</th>
                  {% for item in object_list reversed %}
                  <td class="amount lv1-bottom">{{ item.bs_net_assets|intcomma }}</td>
                  <td class="rate lv1-bottom">{{ item.net_assets_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th></th>
                  {% for item in object_list reversed %}
                  <th colspan="2" width="120px" class="center">
                    <a href="{% url 'financial_analysis:fstatement' item.pk %}">{{ item.fiscal_year }}</a>
                  </th>
                  {% endfor %}
                </tr>
                <tr>
                  <td colspan="9" class="bg-title" style="text-align: left;">損益計算書</td>
                </tr>
                <tr>
                  <td>総売上高</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_gross_sales|intcomma }}</td>
                  <td class="rate">-</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td>売上高総利益</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_gross_profit|intcomma }}</td>
                  <td class="rate">{{ item.gross_profit_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td>営業利益</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_operating_profit|intcomma }}</td>
                  <td class="rate">{{ item.operating_profit_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td>経常利益</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_ordinary_income|intcomma }}</td>
                  <td class="rate">{{ item.ordinary_income_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td>税引き前利益</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_income_before_tax|intcomma }}</td>
                  <td class="rate">{{ item.income_before_tax_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr class="bottom">
                  <td>当期純利益</td>
                  {% for item in object_list reversed %}
                  <td class="amount">{{ item.pl_net_income|intcomma }}</td>
                  <td class="rate">{{ item.net_income_rate|floatformat:1 }}％</td>
                  {% endfor %}
                </tr>
                <tr>
                  <th></th>
                  {% for item in object_list reversed %}
                  <th colspan="2" width="120px" class="center">
                    <a href="">{{ item.fiscal_year }}</a>
                  </th>
                  {% endfor %}
                </tr>
                <tr>
                  <td colspan="9" class="bg-title" style="text-align: left;">キャッシュフロー</td>
                </tr>
                <td>営業ＣＦ</td>
                {% for item in object_list reversed %}
                <td colspan="2" class="amount">{{ item.cf_operating|intcomma }}</td>
                {% endfor %}
                </tr>
                <tr>
                  <td>投資ＣＦ</td>
                  {% for item in object_list reversed %}
                  <td colspan="2" class="amount">{{ item.cf_investment|intcomma }}</td>
                  {% endfor %}
                </tr>
                <tr>
                  <td>財務ＣＦ</td>
                  {% for item in object_list reversed %}
                  <td colspan="2" class="amount">{{ item.cf_finance|intcomma }}</td>
                  {% endfor %}
                </tr>
                <tr class="bottom">
                  <th>合計ＣＦ</th>
                  {% for item in object_list reversed %}
                  <td colspan="2" class="amount">{{ item.cf_total_amount|intcomma }}</td>
                  {% endfor %}
                </tr>
              </table>
              <br>
            </div>
            <!--table responsive-->
          </div>
          <!-- card body -->
        </div>
        <!--card-->
      </div>
      <!--col-->
    </div>

    <!-- ========ここから追加======== -->
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-header d-flex align-items-center">
            <h3 class="h4">推移グラフ</h3>
          </div>
          <!--card header-->
          <div class="card-body">
            <canvas id="myChart" width="400" height="200"></canvas>
            <script>
              var ctx = document.getElementById('myChart').getContext('2d');
              var label_fyear = [{% for item in object_list reversed %} "{{ item.fiscal_year }}", {% endfor %}];
              var data_sales = [{% for item in object_list reversed %} "{{ item.pl_gross_sales }}", {% endfor %} ];
              var data_gross_profit = [{% for item in object_list reversed %} "{{ item.pl_gross_profit }}", {% endfor %} ];
              var data_operating_profit = [{% for item in object_list reversed %} "{{ item.pl_operating_profit }}", {% endfor %} ];

              var data_total_assets = [{% for item in object_list reversed %} "{{ item.bs_total_assets }}", {% endfor %} ];
              var data_fixed_liabilities = [{% for item in object_list reversed %} "{{ item.bs_fixed_liabilities }}", {% endfor %} ];
              var data_net_assets = [{% for item in object_list reversed %} "{{ item.bs_net_assets }}", {% endfor %} ];

              var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                  labels: label_fyear,
                  datasets: [{
                    label: '売上高',
                    data: data_sales,
                    type: 'line',
                    fill: false,
                    lineTension: 0,
                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                    borderColor: 'rgba(255, 99, 132, 1)',
                    borderWidth: 2,
                  }, {
                    label: '売上総利益',
                    data: data_gross_profit,
                    type: 'line',
                    fill: false,
                    lineTension: 0,
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 2,
                  }, {
                    label: '営業利益',
                    data: data_operating_profit,
                    type: 'line',
                    fill: false,
                    lineTension: 0,
                    backgroundColor: 'rgba(255, 206, 86, 0.2)',
                    borderColor: 'rgba(255, 206, 86, 1)',
                    borderWidth: 2,
                  }, {
                    label: '総資産',
                    data: data_total_assets,
                    backgroundColor: 'rgba(75, 192, 192, 0.2)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1,
                  }, {
                    label: '固定負債',
                    data: data_fixed_liabilities,
                    backgroundColor: 'rgba(255, 159, 64, 0.2)',
                    borderColor: 'rgba(255, 159, 64, 1)',
                    borderWidth: 1,
                  }, {
                    label: '純資産',
                    data: data_net_assets,
                    backgroundColor: 'rgba(153, 102, 255, 0.2)',
                    borderColor: 'rgba(153, 102, 255, 1)',
                    borderWidth: 1,
                  }
                  ]
                },
                options: {
                }
              });
            </script>
          </div>
          <!-- class card body -->
        </div>
        <!-- class card -->
      </div>
      <!-- col -->
    </div>
    <!-- row -->
    <!-- ========ここまで追加======== -->
    {% include 'financial_analysis/pagination.html' %}

  </div>
  <!-- container-fluid -->
</section>
<br>
<br> {% endblock %}

templates/financial_analysis/index.html
{% extends 'financial_analysis/base.html' %} {% block content %}
<script>
    jQuery(function ($) {
        $.extend($.fn.dataTable.defaults, {
            language: {
                url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
            }
        });
        $("#fstatement_list").DataTable({
            "searching": true,     //検索ボックスでのテキスト検索を可能にする
            "paging": true,      //ページングを可能にする
            "ordering": true,      //各項目でのソートを可能にする
            "lengthChange": true,  //件数の切り替え機能を可能にする
        }).columns.adjust().draw();
    });
</script>
<h1>トップページ</h1>

<!-- テーブルの定義 -->
<table id="fstatement_list" width="100%" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th class="text-center" width="40%">会社</th>
            <th class="text-center" width="40%">決算日</th>
            <th class="text-center">LINK</th>
        </tr>
    </thead>
    <tbody>
        {% for item in fstatement_list %}
        <tr class="odd gradeX text-center">
            <td class="text-center">{{ item.company}}</td>
            <td class="text-center">{{ item.fiscal_year }}</td>
            <td>
                <a href="{% url 'financial_analysis:fstatement' item.pk %}">詳細へ</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- テーブルの定義 終了-->

{% endblock %}

templates/financial_analysis/pagination.html
<!-- {% if is_paginated %} -->
<div class="pagination-bar">
  <nav aria-label="List pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">前へ</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">前へ</span>
      </li>
      {% endif %} {% for page_num in paginator.page_range %} {% if page_obj.number == page_num %}
      <li class="page-item">
        <span class="page-link active">
          {{ page_num }}
          <span class="sr-only">(current)</span>
        </span>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
      </li>
      {% endif %} {% endfor %} {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">次へ</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">次へ</span>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
<!-- {% endif %} -->